### PR TITLE
Feature/event card component

### PR DESCRIPTION
**Pull request by jakanoh17**
This is a request to pull in part of the changes for the events calendar.

**Parts that are done:**
- Setup to pull in data from Supabase (specifically events data)
-  Layout for events cards and page
- Pagination element (wo working functionality)

**Parts to be completed in future PR:**
- Upcoming and past tabs
- Working pagination functionality
- attend button in event cards (easy add, I just overlooked it)

_There are some elements of the design that I don't think would be possible to implement:_
- attendees profile page pictures -- this info is not in the supabase
- event locations -- info not in supabase

image
I am not too sure about what to do with the "Any type" dropdown. How is it supposed to function?

### CODE REVIEW

**Comment by jakanoh17** [comment]
I've submitted all parts of the event calendar feature and am ready for a complete review

**Comment by Valtaire-O** [comment]
In response to the question about the drop down, its a filter for specific event types
As as far as attendees faces it's not a necessity or even very useful. I'll update the table with locations

**Comment by Valtaire-O** [comment]
So this looks awesome. A few things 

1. The p text should be black so its visible ( ik its grey on the figma but...)
2.  This is a feature , but if theres no upcoming events, the default view should be past, seems like a simple if then condition no?
3. For the url and key creds for supabase, are you thinking to use github secrets? since when its live we'll need someway to access that env file

**Comment by jakanoh17** [comment]
1. Will do
2. This would just be updating one line of code, so no prob there
3. Honestly hadn’t thought about it but thats a good idea, i’ll take care of it

Will have everything done before the meeting tonight

**Pull request merged**
