### PR TITLE
Feature/favicon

### PR DESCRIPTION
**Pull request by bsgauthierwebdev**
I created a PNG image from the BCC logo and added it to the Public folder. I imported the image into the index.html file as a favicon.

### CODE REVIEW

**Comment by Valtaire-O** [comment]
Getting this error when trying to run dev 

  }
  17 |  import { useState } from "react";
  18 |  import { uid } from "uid";
     |                       ^
  19 |  import SponsorCard from "../SponsorCard/SponsorCard";
  20 |  import "./Sponsors.css";

Pre-transform error: Failed to resolve import "uid" from "src/components/Sponsors/Sponsors.jsx". Does the file exist?

**Comment by bsgauthierwebdev** [comment]
Odd. That branch shouldn't have that file. I'll have to go back and fix things. I'll get it taken care of later this week. Thanks!

**Comment by bsgauthierwebdev** [comment]
Okay, I found the issue; the branch was missing the UID dependency. I went ahead and added it, but now I'm getting a conflict. This is where my inexperience comes in, and I'm not sure what I should and shouldn't touch. Talk to me this evening at Reville Grounds and we can sort it out.

**Comment by markdreed512** [comment]
@bsgauthierwebdev 
The splide link in index.html needs to stay. That's for my carousel. I didn't end up using the react-material-ui-carousel and neglected to remove it from package.json, so that can be removed.  Once you remove it from package.json, run npm install and its dependencies should automatically be removed from package-lock.json. I don't believe we should have a yarn.lock at all, since we are using NPM to manage dependencies, not yarn. I think that can be deleted as well.

**Comment by bsgauthierwebdev** [comment]
Okay, let's try this again. I merged all of the upstream changes and re-added the favicon. To use every developer's favorite response: "It's working on my end!"

**Review by bsgauthierwebdev — COMMENTED** [review]
I added the favicon link back into the index.html file

**Pull request merged**
